apiVersion: v1
kind: Pod
metadata:
  name: pod2

spec:
  containers:
  - image: mahendrshinde/myweb:1
    name: web1
    resources:
      limits:
        cpu: '100m'
        memory: '32M'
    ports: 
    - containerPort: 80

  - image: mysql:5.7
    name: db
    env:
      - name: MYSQL_USER
        value: mahendra
      - name: MYSQL_PASSWORD
        value: 'password@1234'
      - name: MYSQL_ROOT_PASSWORD
        value: 'Pass@12345'
      - name: MYSQL_DATABASE
        value: db1
    resources:
      limits:
        cpu: '200m'
        memory: '128M'
    ports: 
    - containerPort: 3306
      
