apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: mahendra
  labels:
    name: testpod
spec:
  nodeSelector:
    kubernetes.io/os: linux 
  containers:
  - name: testpod
    image: mysql:5.7
    envFrom:
        - configMapRef:
            name: cm1
    ports:
      - containerPort: 3306
