apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  namespace: mahendra
  labels:
    name: testpod2
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: testpod2
      image: mysql:5.7
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: cm1
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: cm1
      ports:
        - containerPort: 3306
